services:
  admin-web-server:
    image: ghcr.io/champyod/cms-docker-core:major-admin-panel
  admin-panel-next:
    image: ghcr.io/champyod/cms-docker-admin-panel:major-admin-panel
  ranking-web-server:
    image: ghcr.io/champyod/cms-docker-core:major-admin-panel
